### ISSUE TITLE
Regexp::Syntax::Ruby::* does not implement: [escape:codepoint_list]

### ISSUE THREAD

**Issue by backus** [ammar/regexp_parser#13]
(I'm not sure if I'm using the right terminology here so if my description doesn't make sense then just look at the irb snippet below)

It looks like `regexp_parser` successfully scans for `escape:codepoint_list` tokens but the different ruby version syntax classes don't say they implement this type of node.

Example:

```ruby
2.3.0 :001 > codepoint_list_regex = /\u{9879}/
 => /\u{9879}/
2.3.0 :002 > require 'regexp_parser'
 => true
2.3.0 :003 > Regexp::Parser.parse(codepoint_list_regex)
Regexp::Syntax::NotImplementedError: Regexp::Syntax::Ruby::V230 does not implement: [escape:codepoint_list]
```

I have a fix which I should be able to PR soon

**Comment by ammar** [comment]
@backus, Nice, and thanks again. I rarely use those sequences.

I'm sure that Unicode support, including in RegExp, came with 1.9 (Oniguruma). 1.8 did not support Unicode, pretty much at all.

With **1.8.7-p375**
```ruby
# It seems like it accepts the pattern
>> regex = /\u{41}/
=> /\u{41}/

# But it doesn't match what is expected
>> 'A' =~ regex
=> nil

# It actually matches 41 escpaed u's
>> ("\u" * 41) =~ regex
=> 0

# A code point list raises a warning
>> regex = /\u{41 42}/
(irb):3: warning: regexp has invalid interval
(irb):3: warning: regexp has `}' without escape
=> /\u{41 42}/
```

With **1.9.3-p551**
```ruby
>> regex = /\u{41}/
=> /\u{41}/

# Matches as expected
>> 'A' =~ regex
=> 0

# So does a code point list
>> regex = /\u{41 42}/
=> /\u{41 42}/
>> 'AB' =~ regex
=> 0
>> 'AC' =~ regex
=> nil
```

I think the new `Escape::Unicode` token belongs in the 1.9.1 syntax file.

Cheers

**Comment by backus** [comment]
Thanks @ammar. I'll make the change later today

**Comment by mbj** [comment]
Sorry to highjack this thread but maybe its time to stop supporting 1.8 features (or the absence of these) to reduce overall project complexity and maintenance work?

**Comment by ammar** [comment]
@mbj I'm little torn about completely dropping support for 1.8.

I'm certain about dropping support for it as a runtime version (it's forced), but I wonder if keeping the lineage of 1.8 syntax and tokens might be of value. If not, then it would be a matter of copying those tokens to the oldest 1.9 syntax file, which it not inaccurate.

Any thoughts?

**Comment by mbj** [comment]
> Any thoughts?

I always argue when I drop ruby versions support for my gems (and I do it quite aggresively, as my OSS policy states: Only support what I need!): Use an older version if you need support for old rubies.

Works quite well for me.

**Comment by backus** [comment]
> I always argue when I drop ruby versions support for my gems (and I do it quite aggresively, as my OSS policy states: Only support what I need!): Use an older version if you need support for old rubies.

Adding to what @mbj said ^ here:

>  I wonder if keeping the lineage of 1.8 syntax and tokens might be of value.

It sounds like you're saying "I'm not using 1.8 syntax but it might be of value to others." If that is true then definitely remove 1.8 syntax next time it gets in your way. If people are getting value from it then they'll reveal themselves by opening issues and possibly offering to contribute. Maintaining features for the sake of users which may not exist though is a good way to burnout.
