### ISSUE TITLE
Release 2.3.1 syntax?

### ISSUE THREAD

**Issue by backus** [ammar/regexp_parser#22]
The current release doesn't have a syntax file for ruby 2.3.1.

**Comment by ammar** [comment]
I needed to check the ChangeLog to see if new regexp features have been added 2.3.1. Looks like it's just bug fixes.

Will be committing this shortly too.

**Comment by mbj** [comment]
@ammar Thx! Can you get us a release?

**Comment by ammar** [comment]
@mbj Yes. I wanted to include a fix for the broken `\h` and `\H`that @backus reported in #21 in the release. I just committed a fix for that.

**Comment by mbj** [comment]
@ammar Cool. Thx. Sorry for all this "pressure", I hope its alright for you.

**Comment by ammar** [comment]
@mbj No worries at all. Truly happy to help and sorry I couldn't get to it sooner. It's been on my TODO list for too long, so thanks for the "pressure"

**Comment by ammar** [comment]
And I forgot to mention that 0.3.4 is now released

**Comment by mbj** [comment]
@ammar Thx. I can assure you the "pressure" will be ongoing ;)
