### ISSUE TITLE
Add `Regexp::Syntax.supported?`

### ISSUE THREAD

**Issue by backus** [ammar/regexp_parser#23]
It would be nice if I could do something like

``` ruby
Regexp::Syntax.supported?('ruby/2.3')   # => true
Regexp::Syntax.supported?('ruby/2.3.1') # => false
```

This would make it easier to determine which version to use for `Regexp::Parser`. This is motivated by https://github.com/mbj/mutant/issues/595

**Comment by ammar** [comment]
Good idea.

One possible take could be:
```ruby
def self.supported?(version)
  begin
    self.load(version)
    self.instantiate(version)
    true
  rescue
    false
  end
end
```

That feels a bit brute force though. I would like to think about it a little. Please let me know if you have any ideas.

**Comment by backus** [comment]
I would refactor extract a mapping of names to constants like so:

```ruby
SYNTAX_MAP = {
  # Ruby 1.8.x (NOTE: 1.8.6 is no longer a supported runtime,
  # but its regex features are still recognized.)
  'ruby/1.8.6' => Regexp::Syntax::Ruby::V186,
  'ruby/1.8.7' => Regexp::Syntax::Ruby::V187,

  # alias for the latest 1.8 implementation
  'ruby/1.8'   => Regexp::Syntax::Ruby::V18,

  # Ruby 1.9.x
  'ruby/1.9.1' => Regexp::Syntax::Ruby::V191,
  'ruby/1.9.2' => Regexp::Syntax::Ruby::V192,
  'ruby/1.9.3' => Regexp::Syntax::Ruby::V193,

  # alias for the latest 1.9 implementation
  'ruby/1.9'   => Regexp::Syntax::Ruby::V19,

  # Ruby 2.0.x
  'ruby/2.0.0' => Regexp::Syntax::Ruby::V200,

  # aliases for the latest 2.0 implementations
  'ruby/2.0'   => Regexp::Syntax::Ruby::V20,

  # Ruby 2.1.x
  'ruby/2.1.0' => Regexp::Syntax::Ruby::V210,
  'ruby/2.1.2' => Regexp::Syntax::Ruby::V212,
  'ruby/2.1.3' => Regexp::Syntax::Ruby::V213,
  'ruby/2.1.4' => Regexp::Syntax::Ruby::V214,
  'ruby/2.1.5' => Regexp::Syntax::Ruby::V215,
  'ruby/2.1.6' => Regexp::Syntax::Ruby::V216,
  'ruby/2.1.7' => Regexp::Syntax::Ruby::V217,
  'ruby/2.1.8' => Regexp::Syntax::Ruby::V218,

  # aliases for the latest 2.1 implementations
  'ruby/2.1'   => Regexp::Syntax::Ruby::V21,

  # Ruby 2.2.x
  'ruby/2.2.0' => Regexp::Syntax::Ruby::V220,
  'ruby/2.2.1' => Regexp::Syntax::Ruby::V221,
  'ruby/2.2.2' => Regexp::Syntax::Ruby::V222,
  'ruby/2.2.3' => Regexp::Syntax::Ruby::V223,
  'ruby/2.2.4' => Regexp::Syntax::Ruby::V224,

  # aliases for the latest 2.2 implementations
  'ruby/2.2'   => Regexp::Syntax::Ruby::V22,

  # Ruby 2.3.x
  'ruby/2.3.0' => Regexp::Syntax::Ruby::V230,

  # alias for the latest 2.3 implementation
  'ruby/2.3'   => Regexp::Syntax::Ruby::V23
}
private_constant(:SYNTAX_MAP)

# ...

def self.supported?(name)
  SYNTAX_MAP.key?(name)
end

def self.instantiate(name)
  SYNTAX_MAP.fetch(name) { raise UnknownSyntaxNameError.new(name) }
end
```

Assuming this doesn't break anything of course

**Comment by mbj** [comment]
Yeah, a generic exception rescue is a bad idea, as it can hide exceptions NOT triggered by the intent "missing constant".

**Comment by ammar** [comment]
Thanks. I was thinking along the lines of moving the map outside the instantiate as well. That's seems like a good start.

I'm also considering taking advantage of the naming convention to determine the mapping from existing files. It's cumbersome to update the files and map for new versions.

**Comment by mbj** [comment]
@ammar To reduce maintenance burden you could adapt what the `parser` gem does: Only supporting the very latest ruby patchlevel per minor branch.

This works decently over there.https://github.com/whitequark/parser#compatibility-with-ruby-mri

**Comment by ammar** [comment]
@mbj That approach is tempting.

The only instance of new regexp features being introduced in a tiny version was 1.9.3. Since then things have been stable, with the exception of an occasional upgrade of Unicode properties. Those have only happened on minor versions so far.

The [changes in Unicode 8.0](http://www.unicode.org/versions/Unicode8.0.0/#Database_Changes) appear to have minimal impact on the regexp properties, but I'd like to wait and see when they get added to ruby before deciding on ignoring tiny versions.

**Comment by mbj** [comment]
@ammar Also to people that insist on staying on older ruby versions the reply works fine: Than use regexp_parser/mutant/unparser/parser that where around the time the old ruby version was recent.

**Comment by ammar** [comment]
[WIP](https://github.com/ammar/regexp_parser/tree/feature/syntax-refactor-and-supported-method) that will likely require a minor version change.

**Comment by ammar** [comment]
Closing with release of version 0.4.0
