### ISSUE TITLE
Proposal to eliminate warnings

### ISSUE THREAD

**Issue by mbj** [ammar/regexp_parser#25]
Right now `regexp_parser` controlled code can generate warnings. On projects that have warnings enabled (such as mutant) and have the warning generating call side in the main loop: This can lead megabytes of warnings in the build logs.

This proposoal is about:

1.  [ ] Getting agreement on removing *all* warnings from regexp_parser
2.  [ ] Removing all warnings
3.  [ ] Getting agreement on making the build fail in future in the presence of warnings
4.  [ ] Enforce warnings are absent on the build

I'm happy to take 2. and 4. in case @ammar agrees to 1. and 4.

**Comment by ammar** [comment]
@mbj, I completely agree. Can you please point me to a reproducible case.

**Comment by mbj** [comment]
Reproducible case:

* This build https://circleci.com/gh/mbj/mutant/2662
* From this PR: https://github.com/mbj/mutant/pull/598
* From this branch: https://github.com/mvz/mutant/tree/fix-timeout-example
* From this ref: https://github.com/mvz/mutant/commit/45ff5713b85890be053efbeea709db1b9c44e1eb

So to reproduce:

* Checkout mutant at that ref
* run `bundle install && bundle exec rspec spec/integration/mutant/corpus_spec.rb`

As you asked for a reproducible case I gave you ^^. If you wanted I could get you a minimized reproduction that will likely not involve mutant. But for now I saved myself the time.

In theory you *just* have to enable warnings in your build to get all of them (assuming decent coverage).

**Comment by ammar** [comment]
Got it. That should be enough. Thanks.

**Comment by mbj** [comment]
@ammar Does this mean you want to eliminate warnings by yourself (and enforce they do not come back?) or you understand the case and want me to do it (as I offered)?

**Comment by ammar** [comment]
Found a simple way to reproduce thanks to @mbj hint:

```
ruby -w -Ilib test/test_all.rb
```

Not sure those are all the warnings, but that's a start.

**Comment by ammar** [comment]
@mbj, I'm happy to take it on.

**Comment by mbj** [comment]
> Not sure those are all the warnings, but that's a start.

By default I fix all of them. Just for removing the need for whitelisting.

**Comment by backus** [comment]
I'd be interested in integrating something like mutant's [`WarningFilter`](https://github.com/mbj/mutant/blob/fix/regexp_parser-unsupported/lib/mutant/warning_filter.rb) for the sake of capturing warnings emitted during tests so we can assert "tests did not emit errors"

**Comment by mbj** [comment]
@ammar If you plan to PR your fixes, I'd be happy to review them to make sure we get the most out of it.

The more devs look at stuff the better it gets. I do not want to "heckle" you in any way, but maybe we can catch a thing that would result in another iteration we can spare with a review, or more likely I ask a dump question on the code and with your reply learn something on the inner workings of `regexp_parser`.

**Comment by backus** [comment]
@ammar can we invite you to the mutant slack channel? Should make communicating about this stuff a bit easier.

**Comment by ammar** [comment]
@backus Yes, please do.

**Comment by backus** [comment]
@ammar invited (using your email from your github profile)

**Comment by ammar** [comment]
Fixed with the release of 0.3.6

Thanks @backus
