### ISSUE TITLE
Nested repetitions parsed potentially incorrectly

### ISSUE THREAD

**Issue by calfeld** [ammar/regexp_parser#3]
Summary: /o{2}{5}/ matches 10 o's (in ruby) but the {2} quantifier is lost in the parse tree.

Example code:

```
#!/usr/bin/env ruby

require 'rubygems'
require 'regexp_parser'
require 'pp'

re = /o{2}{5}/
pp Regexp::Parser.parse(re)

puts "o" if "o" =~ re
puts "2 o" if "o"*2 =~ re
puts "5 o" if "o"*5 =~ re
puts "10 o" if "o"*10 =~ re
```

Output:

```
#<Regexp::Expression::Root:0x105fd9d40
 @expressions=
  [#<Regexp::Expression::Literal:0x105fd6398
    @expressions=[],
    @options=nil,
    @quantifier=
     #<Regexp::Expression::Quantifier:0x105fd5e20
      @max=5,
      @min=5,
      @mode=:greedy,
      @text="{5}",
      @token=:interval>,
    @text="o",
    @token=:literal,
    @type=:literal>],
 @options=nil,
 @text="",
 @token=:root,
 @type=:expression>
10 o
```

Comments:

As far as I can tell, the nested quantifier syntax isn't documented in ruby and is illegal in pcre.  Grep for example, will not match any number of o's for the given regexp.  As such, I'd be content with a will-not-fix verdict.  But I thought you might be interested.

Thank you for your time.

**Comment by jaynetics** [comment]
@ammar in light of the discussion in #63 we might want to deal with this at well. i've actually seen this in use, e.g. to validate css hex colors: `/\A\h{3}{1,2}\z/`.

should i make an attempt?

if so, would passive groups or some new node be more appropriate to accomodate the extra quantifiers? the latter would warrant a major version bump in my opinion, so i'm more inclined to use passive groups, and maybe add `Group::Passive#implicit?` to allow differentiating.

**Comment by calfeld** [comment]
I applaud your consideration of a 7 year old bug.

**Comment by ammar** [comment]
@jaynetics Sure, if you can. Happy to support and review too.

> if so, would passive groups or some new node be more appropriate to accomodate the extra quantifiers?

That would work, but I haven't thought about it much. I wonder if makes it sense for quantifier nodes to have an internal quantifier stack. It might be instructive to find out how Onigmo represents these cases in its parse tree.

**Comment by jaynetics** [comment]
the solution proposed by @calfeld is now live with v2.0.0 - better late than never 😆
