### ISSUE TITLE
Ruby 2.2.7 syntax missing

### ISSUE THREAD

**Issue by graaff** [ammar/regexp_parser#41]
There is no syntax file for ruby 2.2.7, which means that on a current ruby 2.2 the code now fails with "Regexp::Syntax::UnknownSyntaxNameError: Unknown syntax name 'ruby/2.2.7'. Forgot to add it in the case statement?". I realize that ruby 2.2 is old, but it is still officially maintained until March 2018.

**Comment by ammar** [comment]
Thanks @gjtorikian for reporting this, and sorry for the delay.

And thanks @janosch-x for the PR. It was just merged. The recent ruby versions (2.2.8, 2.35. and 2.4.2) were also added.

**Comment by gjtorikian** [comment]
cc @graaff 😉

**Comment by graaff** [comment]
Thanks!

**Comment by ammar** [comment]
Oops. Wrong name that starts with a <kbd>g</kbd>. Sorry for the noise.
