### ISSUE TITLE
Ruby 2.4.3 raising errors

### ISSUE THREAD

**Issue by aselder** [ammar/regexp_parser#48]
Similar to https://github.com/ammar/regexp_parser/issues/41,

we're getting errors running under Ruby 2.4.3:

`Unknown syntax name 'ruby/2.4.3'. Forgot to add it to Regexp::Syntax::VERSIONS?`

**Comment by janosch-x** [comment]
Hi @aselder 

thanks for bringing this up!

I've just released version 0.4.8 with support for the latest Rubies.

Cheers
Janosch
