### ISSUE TITLE
Ruby 2.5.0 support

### ISSUE THREAD

**Issue by jerryjohnjacob** [ammar/regexp_parser#51]
Getting a `Regexp::Syntax::UnknownSyntaxNameError` on Ruby 2.5.0:

    Unknown syntax name 'ruby/2.5.0'. Forgot to add it to Regexp::Syntax::VERSIONS?

When would support for 2.5.0 be available?

**Comment by ammar** [comment]
Support for 2.5.0 was added by #50. Please upgrade to 0.4.9.

**Comment by jerryjohnjacob** [comment]
@ammar I got the above issue on 0.4.9
