### ISSUE TITLE
Ruby 2.3.7 support

### ISSUE THREAD

**Issue by JasonBarnabe** [ammar/regexp_parser#54]
And 2.2.10, but I don't care so much about that one :)

**Comment by janosch-x** [comment]
Can you resolve this the classical way by adding the classes, @ammar ?

I'd still like to clean the other PR up a bit and am AFK for a week.

Jason Barnabe <notifications@github.com> schrieb am Mo., 2. Apr. 2018,
15:46:

**Comment by ammar** [comment]
Will do @janosch-x. Thanks!

**Comment by ammar** [comment]
Released v0.4.13 with support for Ruby 2.2.10 and 2.3.7.
