### ISSUE TITLE
Support for Unicode blocks?

### ISSUE THREAD

**Issue by gjtorikian** [ammar/regexp_parser#8]
I noticed that Unicode blocks are not supported in https://github.com/ammar/regexp_parser/blob/3f03b4d121e8c52c1a27a5d515fa6f5b81a0843b/lib/regexp_parser/syntax/tokens/unicode_property.rb#L103.

Unicode blocks are basically like ranges of Unicode script: http://www.regular-expressions.info/unicode.html#block

I'm happy to make a PR for this if it's helpful.

**Comment by ammar** [comment]
Definitely an omission. Thanks for pointing it out.

I would love to add support for Unicode blocks but it might be a while before I get the time. A PR would be most welcome. Cheers!
