### ISSUE TITLE
2.9.0 gem not found

### ISSUE THREAD

**Issue by muripic** [ammar/regexp_parser#89]
Dependabot rubocop-rspec upgrades are installing the new version of regexp_parser, 2.9.0. However, we are getting this error:

```
➜  bundle install
Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to regexp_parser (2.9.0) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in that source. That means the author of regexp_parser (2.9.0) has removed it. You'll need to update your bundle to a version other than regexp_parser (2.9.0) that hasn't been removed in order to install.
```

This is the diff from the rubocop-rspec upgrade:

<img width="655" alt="Screenshot 2024-01-08 at 13 55 59" src="https://github.com/ammar/regexp_parser/assets/24720032/a44204c4-12d4-4637-8359-86bcf2f06149">

**Comment by CvX** [comment]
We also had issues with installing 2.9.0 at [discourse](https://github.com/discourse/discourse) but I'm now able to install it locally 🤔 

```
❯ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching regexp_parser 2.9.0
Installing regexp_parser 2.9.0
Bundle complete! 138 Gemfile dependencies, 234 gems now installed.
```

**Comment by muripic** [comment]
Indeed, now it's working for me too, so closing the issue ✅

**Comment by jaynetics** [comment]
JFYI this might have been the cause: https://github.com/rubygems/rubygems.org/issues/4331
